### ISSUE TITLE
Curve sampling resolution option

### ISSUE THREAD

**Issue by brendon** [codelastnight/to-path-figma#23] opened 2020-10-27 23:12 UTC
Hi there,

I remember there being an option that would allow one to change the resolution of the curve sampling so that text at smaller sizes would have a more even flow. It looks like this has been removed?

I've noticed when dealing with smaller text sizes, the gaps between the letters can be quite uneven.

Is it possible to have this option reinstated? :)

**Comment by codelastnight** [comment] 2020-11-29 22:11
Hi! Sorry for not responding, I've been busy with life etc... I remember removing this due to a conflict in the code but I'll put this back in the coming week or so (i think)

**Comment by brendon** [comment] 2020-11-29 22:20
Thanks @codelastnight :) Absolutely no problem at all :D No rush!

**Comment by codelastnight** [comment] 2020-12-04 01:49
I added this back in in version 1.5.1 :) hopefully it still works as intended. Closing this for now, but you can re-open if there's issues with the precision setting.

**Closed by codelastnight** 2020-12-04 01:49 UTC

**Comment by brendon** [comment] 2020-12-04 19:22
Thanks @codelastnight :) Much appreciated. I'll give it a whirl on the next project :)
